{"body": "\n[](http://api.ning.com:80/files/f-5dhOEsZkuZru04SJFSuRYCKvt8u2oPfuX9qo5qhaES6B4X8me*tNhWd0fq88WlVm3oqeaCJFWbusMnWe51zyPhqfMvS7vI/connect.PNG)\n\nSame error. So it has something to do with how the internet security they have at my workplace deals with the way component collects data.[<img class=\"align-full\" height=\"244\" src=\"http://api.ning.com:80/files/f-5dhOEsZkuZru04SJFSuRYCKvt8u2oPfuX9qo5qhaES6B4X8me*tNhWd0fq88WlVm3oqeaCJFWbusMnWe51zyPhqfMvS7vI/connect.PNG?width=721\" width=\"422\"/>](http://api.ning.com:80/files/f-5dhOEsZkuZru04SJFSuRYCKvt8u2oPfuX9qo5qhaES6B4X8me*tNhWd0fq88WlVm3oqeaCJFWbusMnWe51zyPhqfMvS7vI/connect.PNG)I changed a boolean in the py which generates the error statement. It generates this error then -\n\n[<img class=\"align-full\" height=\"116\" src=\"http://api.ning.com:80/files/f-5dhOEsZkvzV0cPpfRKIpiwvQlqyA*vkubXWHdWunkFaSwW1vHsHFi6S271RladMclwLvBLtql*HkkuaCzQpiaFCWga4X2r/connect1.PNG\" width=\"420\"/>](http://api.ning.com:80/files/f-5dhOEsZkvzV0cPpfRKIpiwvQlqyA*vkubXWHdWunkFaSwW1vHsHFi6S271RladMclwLvBLtql*HkkuaCzQpiaFCWga4X2r/connect1.PNG)\n\n\n", "attachments": [], "created_by_name": "Saket Sarupria", "created_at": "January 24, 2017 at 02:24AM", "created_by": "SaketSarupria", "parent_id": "reply_2985220_Comment_1677415", "id": "reply_2985220_Comment_1677423"}